# Generated by Django 4.0.2 on 2022-02-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_label_assignees_issue_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
