# Generated by Django 4.0.2 on 2022-02-19 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_issue_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now),
        ),
    ]
