# Generated by Django 4.0.2 on 2022-03-15 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_project_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assignees',
            field=models.ManyToManyField(related_name='issue_assignees', to=settings.AUTH_USER_MODEL),
        ),
    ]
